- README.md
> Add Scaleway upload provider

- README.md
> Add new email provider : sendinblue

- README.md
> Add new upload provider : Google Cloud Storage

- README.md
> Add WeTransfer upload provider

- README.md
> ADD: Caching middleware

- README.md
[Link to project repo](https://github.com/malgamves/strapi-starter-minimal-sapper-blog)
I built a site with Sapper and I think it should be added here because there aren't any other examples with it.
> Adding a Sapper Blog Starter to the list

- README.md
> Add Responsive image community plugin

- README.md
As per discussion in Slack and here https://github.com/strapi/strapi/issues/2100, I would like to add a new  plugin which displays Entity Relationship Chart of all models.
> Community plugin strapi-plugin-entity-relationship-chart

- README.md
> Add new email provider : nodemailer

- README.md
> docs: adds toastui based wysiwyg

- README.md
Hi all, 
Let me know if the package is missing anything needed to have it listed here.
Thanks, 
George Kemp
> Adds HubSpot Upload Provider

- README.md
> Add Image Api community plugin

- README.md
Introducing community plugin created recently.
> strapi-plugin-comments

- README.md
- [x ] I have read the [contribution guidelines](https://github.com/strapi/awesome-strapi/blob/master/CONTRIBUTING.md) thoroughly.
- [x ] I ensure my submission follows each and every point.
> Moesif plugin

- README.md
Because the development of an Algolia plugin will probably take some time, it would be nice to mention the existence of the hook here because it could be useful for someone.
> Add Algolia hook

- README.md
> Added Strapi Forum in README.md

- README.md
> Add oEmbed plugin

- README.md
> [add] Scaffold, Plugin & SDK

- README.md
Introducing community plugin created recently.
> Navigation builder plugin

- README.md
- Rename image-api to zeasy-image-api with new GitHub link
- Add React MD Editor plugin
> Add React MD Editor plugin and rename plugin

- README.md
> Remove duplicate ToastUI link

- README.md
Introducing a new middleware for caching uploaded assets as discussed in https://github.com/strapi/strapi/pull/8654
> Add strapi-middleware-upload-plugin-cache

- README.md
Add new [CKEditor 5 plugin](https://github.com/Roslovets-Inc/strapi-plugin-ckeditor5) that works with the latest version of Strapi without bugs and based on [enhaced build of CKEditor](https://github.com/Roslovets-Inc/ckeditor5-build-strapi-wysiwyg).
> Add enhanced CKEditor 5 plugin

- README.md
I'm happy to contribute to the Strapi community plugin's growth w/ this piece of software I've just created.
> Add email-designer plugin

- README.md
> Add Video Thumbnail plugin to README

- .editorconfig
- .prettierrc.js
- README.md
> Cleanup the readme and add some missing templates + move editors

- README.md
- [ x] I have read the [contribution guidelines](https://github.com/strapi/awesome-strapi/blob/master/CONTRIBUTING.md) thoroughly.
- [ x] I ensure my submission follows each and every point.
> add strapi-plugin-sync-roles-permissions

- README.md
Signed-off-by: ScottAgirs <scott@ijs.to>
> feat: Add strapi-plugin-migrate

- README.md
Signed-off-by: ScottAgirs <scott@ijs.to>
> feat: Add strapi-provider-email-mailjet

- README.md
Hi, I recently created a custom Strapi plugin.
Take a look at it and tell me what you think about it.
Kind regards!
> Add strapi-plugin-point-list

- README.md
> Added strapi-provider-email-mailtrap

- README.md
Hello... Just published our first Strapi Plugin. It lets you publish content changes using a GitHub Actions workflow.
Link to plugin [here](https://github.com/phantomstudios/strapi-plugin-github-publish).
> Add strapi-plugin-github-publish to the community plugins

- README.md
Plugin to easily manage database config (core_store e.g.) across environments.
> Add strapi-plugin-config-sync to the community plugins

- README.md
Hello !
I've finished today to write this new plugin, I need beta test and feedback about it :) 
Hope the community will enjoy it !
Best ❤️
> Add strapi-plugin-notification-expo

- README.md
Raw Query allows you to send raw query strings to the database.
> Add Raw Query Plugin

- README.md
> Replace Slack link by Discord

- README.md
> Add international fields plugin

- README.md
I don't really know if the plugin is mature enough to be listed, but to keep improving it I will need external feedback. And the testing community around Strapi seems to be relatively small.
For example I was planning on breaking it down in two plugins, one for mocking and one for testing. But I'm not sure. 
And I haven't tested it in multiple machines, which may be needed because the plugin is doing some file manipulation to create the boilerplate.
Any idea on how to get feedback? 
Thanks
> add testing community plugin

- README.md
Hi I am currently tinkering on an authorization module for Angular.
NgxStrapiAuth is a Angular library that implements all standard operations like logging in or registering a user. Services and guards are also provided, as well as ready-made components.
The goal of this project is to implement standard functionalities so that a developer does not have to deal with these tasks unnecessarily. There is still a lot to do to improve the library and make it more dynamic.
I was not really sure where to place my entry in the list. I am sorry if it is wrong. 
Link to the repository: https://github.com/jabali2004/ngx-strapi-auth
> Add auth library for angular

- README.md
> Add Editor.js plugin

- README.md
I simply added a community plugin made for Medusa x Strapi.
> Add medusa-plugin-strapi in the community plugins

- README.md
Updated the whole readme to make it clear the separation of v3/v4
> Update for v4

- README.md
> Add information about Passwordless plugin
